-- app.care_team_member definition

-- Drop table

-- DROP TABLE app.care_team_member;

CREATE TABLE app.care_team_member (
	ctm_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	team_id int4 NOT NULL,
	userid int4 NULL,
	"name" varchar(100) NULL,
	email varchar(150) NULL,
	roleid int4 NULL,
	saved_toolkit _int4 NOT NULL DEFAULT '{}'::integer[],
	inserted_at timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	updated_by int4 NULL,
	inserted_by int4 NULL,
	timezoneid int4 NULL,
	CONSTRAINT care_team_member_pkey PRIMARY KEY (ctm_id)
);


-- app.care_team_member foreign keys

ALTER TABLE app.care_team_member ADD CONSTRAINT care_team_member_roleid_fkey FOREIGN KEY (roleid) REFERENCES meta.team_role(roleid);
ALTER TABLE app.care_team_member ADD CONSTRAINT care_team_member_team_id_fkey FOREIGN KEY (team_id) REFERENCES app.care_team(team_id);